-- MySQL Script generated by MySQL Workbench
-- 03/28/17 20:15:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projeto_tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_tcc` DEFAULT CHARACTER SET latin1 ;
USE `projeto_tcc` ;

-- -----------------------------------------------------
-- Table `projeto_tcc`.`perfil_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_tcc`.`perfil_usuario` (
  `id` INT(11) NOT NULL,
  `tipo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projeto_tcc`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_tcc`.`administrador` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NULL DEFAULT NULL,
  `id_perfil_FK` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_perfil_FK` (`id_perfil_FK` ASC),
  CONSTRAINT `administrador_ibfk_1`
    FOREIGN KEY (`id_perfil_FK`)
    REFERENCES `projeto_tcc`.`perfil_usuario` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projeto_tcc`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_tcc`.`cliente` (
  `id` INT(11) NOT NULL,
  `NOME` VARCHAR(50) NULL DEFAULT NULL,
  `CPF` VARCHAR(50) NULL DEFAULT NULL,
  `ENDERECO` VARCHAR(50) NULL DEFAULT NULL,
  `TELEFONE` VARCHAR(50) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(50) NULL DEFAULT NULL,
  `LOGIN` VARCHAR(50) NULL DEFAULT NULL,
  `SENHA` VARCHAR(50) NULL DEFAULT NULL,
  `id_perfil_FK` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_perfil_FK` (`id_perfil_FK` ASC),
  CONSTRAINT `cliente_ibfk_1`
    FOREIGN KEY (`id_perfil_FK`)
    REFERENCES `projeto_tcc`.`perfil_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projeto_tcc`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_tcc`.`funcionario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(50) NULL DEFAULT NULL,
  `MATRICULA` VARCHAR(50) NULL DEFAULT NULL,
  `DATA_ADMISSIONAL` VARCHAR(30) NULL DEFAULT NULL,
  `LOGIN` VARCHAR(50) NULL DEFAULT NULL,
  `SENHA` VARCHAR(50) NULL DEFAULT NULL,
  `id_perfil_FK` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_perfil_FK` (`id_perfil_FK` ASC),
  CONSTRAINT `funcionario_ibfk_1`
    FOREIGN KEY (`id_perfil_FK`)
    REFERENCES `projeto_tcc`.`perfil_usuario` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projeto_tcc`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_tcc`.`pedido` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(100) NOT NULL,
  `valor` DECIMAL(5,2) NOT NULL,
  `quantidade` INT(11) NOT NULL,
  `total` DECIMAL(6,2) NOT NULL,
  `stats` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projeto_tcc`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_tcc`.`produto` (
  `cod_produto` INT(11) NULL DEFAULT NULL,
  `nome_produto` VARCHAR(50) NULL DEFAULT NULL,
  `valor` DECIMAL(5,2) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
